In [2]:
import functools
import re
import typing
import jax
import jax.numpy as jnp
from jax.scipy.spatial.transform import Rotation


In [47]:
#adapted from https://stackoverflow.com/questions/74519927/best-way-to-rotate-and-translate-a-set-of-points-in-python

def rotate_and_translate(points: jnp.ndarray
                         , center_point: jnp.ndarray, rotation_vector: jnp.ndarray,
                         translation_vector: jnp.ndarray) -> jnp.ndarray:
    rotation_matrix = Rotation.from_rotvec(rotation_vector).as_matrix()
    return (points - center_point) @ rotation_matrix.T + center_point + translation_vector



# rotateMatrix = Rotation.from_rotvec(jnp.array([ jnp.pi,0.0, 0.0])).as_matrix()
points=jnp.array([[0.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, -1.0, 0.0]])
center_point=jnp.array([0.0, 0.0, 0.0])
# newxy = (points-center_point) @ rotateMatrix.T + center_point

newxy=rotate_and_translate(points, center_point, jnp.array([ jnp.pi,0.0, 0.0]), jnp.array([2.0, 2.0, 2.0]))
newxy.round(2)

Array([[2., 2., 2.],
       [2., 1., 2.],
       [2., 3., 2.]], dtype=float32)

In [37]:
import numpy as np
import numpy as np

rott = Rotation.from_rotvec(jnp.array([2*jnp.pi, 0.0, 0.0])).as_matrix()
print(f"rott {rott}")
points=jnp.array([[0.0, 0.0, 0.0], [1.0, 0.0, 0.0], [-1.0, 0.0, 0.0]])
(rott*points).round(2)


# Define the rotation matrix
# r = np.array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00],
#               [0.0000000e+00, 1.0000000e+00, -1.7484555e-07],
#               [0.0000000e+00, 1.7484555e-07, 1.0000000e+00]])

# # Define the 3-dimensional points
# p = np.array([[0.0, 0.0, 0.0],
#               [1.0, 0.0, 0.0]])






# # Apply the rotation matrix to the points
# def rotate_points(p, r, c):
#     # Translate the points to the origin
#     translated_points = p - c
    
#     # Rotate the translated points using the rotation matrix
#     rotated_points = jnp.dot(translated_points, r)
    
#     # Translate the rotated points back to the original position
#     final_points = rotated_points + c
    
#     return final_points

# # Example usage
# p = jnp.array([[0.0, 0.0, 0.0], [1.0, 0.0, 0.0], [-1.0, 0.0, 0.0]])
# r = Rotation.from_rotvec(jnp.array([0.0,0.0, jnp.pi])).as_matrix()
# c = jnp.array([1.0, 1.0, 1.0])

# result = rotate_points(p, r, c)
# print(result.round(2))  




rott [4.371139e-08 0.000000e+00 0.000000e+00]


Array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [-0.,  0.,  0.]], dtype=float32)

In [13]:

def get_fiducial_loos(weights,from_landmarsk,to_landmarks):
    """
    first entries in in weights are :
        0-3 first rotation vector   
        3-6 translation vector   
        6-9 second rotation vector 
    so we interpret the weights as input for transormations rotation;translation;rotation
    we apply this transformation to the fiducial points of moving image and 
    calculate the distance between transformed fiducial points and fiducial points on fixed image           
    """
    
    
    
    
def transform_image(image,weights):
    """
    first entries in in weights are :
    0-3 first rotation vector   
    3-6 translation vector   
    6-9 second rotation vector 
    so we interpret the weights as input for transormations rotation;translation;rotation
    
    """    
    r = Rotation.from_rotvec(jnp.array([0.1, 0.2, 0.3]))
    # imagee= jnp.zeros((3,3,3))

    # Create consecutive array of integers
    imagee = jnp.arange(27)
    imagee = imagee.reshape((3, 3, 3))

    print(imagee)
    # r.apply(imagee).shape
    imagee=jax.image.scale_and_translate(imagee, imagee.shape,jnp.array([0,1,2]), jnp.array([1.0,1.0,1.0]), jnp.array([0.1,0.0,0.0]), "bicubic")
    imagee

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


Array([[[-0.38942468,  0.6105753 ,  1.6105753 ],
        [ 2.6105752 ,  3.6105752 ,  4.610575  ],
        [ 5.610575  ,  6.6105757 ,  7.610575  ]],

       [[ 8.023394  ,  9.023394  , 10.023395  ],
        [11.023394  , 12.023394  , 13.023395  ],
        [14.023395  , 15.023394  , 16.023396  ]],

       [[17.485338  , 18.485338  , 19.485338  ],
        [20.485338  , 21.485338  , 22.485338  ],
        [23.485338  , 24.485338  , 25.485338  ]]], dtype=float32)

In [10]:
r = Rotation.from_rotvec(jnp.array([2*jnp.pi, 0.0, 0.0])) ####### it is in radians
# imagee= jnp.zeros((3,3,3))

# Create consecutive array of integers
imagee = jnp.arange(27)
imagee = imagee.reshape((3, 3, 3))

print(imagee)
imagee=r.apply(imagee)
# imagee=jax.image.scale_and_translate(imagee, imagee.shape,jnp.array([0,1,2]), jnp.array([1.0,1.0,1.0]), jnp.array([0.1,0.0,0.0]), "bicubic")
imagee

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


Array([[[ 0.        ,  0.99999964,  2.0000002 ],
        [ 3.        ,  3.999999  ,  5.0000005 ],
        [ 6.        ,  6.9999986 ,  8.000001  ]],

       [[ 9.        ,  9.999998  , 11.000002  ],
        [12.        , 12.999997  , 14.000002  ],
        [15.        , 15.999997  , 17.000002  ]],

       [[18.        , 18.999996  , 20.000004  ],
        [21.        , 21.999996  , 23.000004  ],
        [24.        , 24.999996  , 26.000004  ]]], dtype=float32)